// Notifications generated by the "Backup Title" flow (see /api/title-drafts and
// /api/title-drafts/adviser) look almost identical to the real Title & Evidence
// Approval notifications — both mention a title, both can say "approved" or
// "needs revision." Without a visual marker they're easy to mistake for a
// decision on the group's actual, live submission. Every UI that lists
// notifications checks a title against this set and renders a small "Backup"
// badge when it matches, so it's unmistakable at a glance which one it is.
const BACKUP_TITLE_NOTIFICATION_TITLES = new Set([
  'Backup Title Awaiting Review',
  'Backup Title Approved',
  'Backup Title Needs Revision'
]);

export function isBackupTitleNotification(title: string | null | undefined) {
  return Boolean(title && BACKUP_TITLE_NOTIFICATION_TITLES.has(title));
}
